name: DEPLOY
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: /
          remote_path: /var/www/ethaielite/
          remote_host: "35.185.176.142"
          # remote_user: ethailandelitevisa
          # remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
